services:
  db:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app
      MARIADB_USER: app
      MARIADB_PASSWORD: app
      TZ: Europe/Berlin
    ports:
      - "3307:3306"        # Host:3307 -> Container:3306
    volumes:
      - db_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-name-resolve
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -proot --socket=/run/mysqld/mysqld.sock --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 120s
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      TZ: Europe/Berlin
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    environment:
      MP_UI_AUTH: "false"
      TZ: Europe/Berlin
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP
    restart: unless-stopped

  app:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    environment:
      APP_ENV: dev
      TZ: Europe/Berlin
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:9000" # php-fpm
    restart: unless-stopped

  web:
    image: nginx:1.27-alpine
    volumes:
      - ./backend:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  db_data: {}